### ISSUE TITLE
Quick Idea

### ISSUE THREAD

**Issue by SorenBarzul** [matlsn/nook#1]
Not sure if this is the correct place
but would it be possible to include a randomized song that is being played, so that over the course of the hour it switches between the games (for example at the end of each games song loop) so that the same one is not played for the full hour?
Thanks!

**Comment by matlsn** [comment]
Definitely possible! Need to work out the logic a bit more in my head here... should it switch between random times as well, or should it always play CURRENT_HOUR in the different games?

**Comment by SorenBarzul** [comment]
My thought was the current hour in the different games
For example, at the end of each song's loop, it would move to a random other game's song for that current hour

**Comment by matlsn** [comment]
I think I like the idea of having a shuffle label followed by a select box that contains ["Shuffle All", "Shuffle Normal", "Shuffle Rain", "Shuffle Snow"]. Gonna add to the to-do list. Thanks for the suggestion!
