### ISSUE TITLE
Music auto-playing randomly

### ISSUE THREAD

**Issue by ihaslibrary** [matlsn/nook#2]
The extension auto plays randomly every hour

I don't make it, I do nothing to it, IT STILL PLAYS

**Comment by matlsn** [comment]
Is grandfather mode on?

**Comment by matlsn** [comment]
Closing because no response and nobody else seems to have this issue

**Comment by ihaslibrary** [comment]
I realized grandfather mode was in on

Thank you!

**Comment by Nemura** [comment]
Same issue here, with grandfather mode on. Firefox v68 (64bit)
