### ISSUE TITLE
whenever a song is finished it fades out and then stops

### ISSUE THREAD

**Issue by Ya-boi-mees** [matlsn/nook#3]
Before the grandfather mode update songs would loop, now I have to press play again and again and again.

**Comment by matlsn** [comment]
Do you have grandfather mode checked?

**Comment by matlsn** [comment]
Closing because same as https://github.com/matlsn/nook/issues/2

**Comment by Nemura** [comment]
Could this issue be reopened? The issue you link to above doesn't seem to exist.
I am having the same problem in Firefox v68 (64bit). One song plays, then fades out slowly and stops playing.
