### ISSUE TITLE
Can't play rain sounds anymore.

### ISSUE THREAD

**Issue by leonardlorenz** [matlsn/nook#4]
The amazonaws link in the source returns forbidden, so I'm guessing it's dead.

line 53 causes the problem, most likely.
https://github.com/matlsn/nook/blob/master/src/timehandler.js
```Javascript
src: [`https://s3.us-east-2.amazonaws.com/chrome-nook/rain/rain.ogg`],
```
A new rain source file has to be found. I could host one temporarily in the meantime if needed. Just tell me if you need me to host a file for you, I couldn't find one yet.

**Comment by matlsn** [comment]
Hey Leonard, I actually finished setting up CloudFront to replace S3 the other day and totally forgot to change the rain URL as well - I'll go ahead and just change the URL. Thanks for your help!

**Comment by matlsn** [comment]
Fixed URL in commit https://github.com/matlsn/nook/commit/0162007bfec7f04def08d12be2c77adc99063541
